// Precompress the hero's model binaries, so the route that serves them has
// something to negotiate with.
//
// WHY THIS EXISTS AT ALL. Next bundles the `compression` middleware, whose
// default filter is `compressible(contentType)` — and `application/octet-stream`,
// which `send` derives from the .bin extension, is not in the compressible set.
// So the 7.27 MB vertex block was going over the wire RAW while every .js chunk
// from the same process got gzip. Measured against the running production server:
// `Content-Length: 7628072` and no `Content-Encoding` header at all. The "brotlis
// to 3.93 MB" the scene's own comment claimed was a property of the file that no
// visitor had ever benefited from.
//
// It cannot be done on the fly. Brotli at quality 11 takes 20.7 s on this file
// and gzip -6 takes 158 ms per request, which is why no server compresses a 7 MB
// octet-stream in the request path — it has to be precomputed, once, at build.
//
// Measured on the shipped binaries, at the levels used below:
//   cad-layers.bin        7,628,072 -> gzip 5,171,673 (-32%) -> br 4,132,280 (-46%)
//   cad-layers-index.bin     27,948 -> gzip    14,215 (-49%) -> br    12,418 (-56%)
//
// Both encodings are emitted because the route negotiates: brotli where the
// client asks for it (every browser since 2016), gzip as the fallback, and the
// raw file for anything that asks for neither.
//
// Run from `prebuild`, so `npm run build` — which is what scripts/deploy.sh runs
// on the server — cannot produce a deployment without them. The outputs are
// gitignored: they are derived bytes, and 4 MB of them would double what this
// repo already carries for the .bin itself.
import { readFile, writeFile, stat } from 'node:fs/promises';
import { brotliCompress, gzip, constants } from 'node:zlib';
import { createHash } from 'node:crypto';
import { promisify } from 'node:util';
import path from 'node:path';

const brotliAsync = promisify(brotliCompress);
const gzipAsync = promisify(gzip);

const ROOT = path.join(import.meta.dirname, '..');
const TARGETS = ['public/models/cad-layers.bin', 'public/models/cad-layers-index.bin'];

// Skip a target whose encodings are already newer than the source. Brotli q11 is
// 21 s on the big file and the binaries change only when Blender re-runs the
// exporter, so an incremental build should not pay it every time.
async function isFresh(src, out) {
  try {
    const [a, b] = await Promise.all([stat(src), stat(out)]);
    return b.mtimeMs >= a.mtimeMs;
  } catch {
    return false;
  }
}

const pct = (n, d) => `${(100 - (100 * n) / d).toFixed(0)}%`;

// Second job, and the reason this script runs on every build rather than by hand:
// checking that MODEL_REV still describes the bytes it is stamping.
//
// The URLs are served immutable for a year and busted only by that stamp, so
// regenerating the geometry without bumping it strands every returning visitor on
// stale meshes — silently, invisibly to every test, for up to a year. The stamp
// lived 5,700 lines away from the exporter with nothing connecting them. Here the
// bytes are already in hand, so the check is free.
const hashes = [];

for (const rel of TARGETS) {
  const src = path.join(ROOT, rel);
  let raw;
  try {
    raw = await readFile(src);
    hashes.push(createHash('sha256').update(raw).digest('hex').slice(0, 12));
  } catch {
    // Not a build failure. The binaries are regenerated by a Blender script that
    // is not part of `npm run build`, and a clone that has not run it should
    // still build — the route falls back to whatever is on disk.
    console.warn(`precompress: ${rel} not found, skipping`);
    continue;
  }

  for (const [ext, run] of [
    ['.br', () => brotliAsync(raw, { params: { [constants.BROTLI_PARAM_QUALITY]: 11 } })],
    ['.gz', () => gzipAsync(raw, { level: 9 })],
  ]) {
    const out = src + ext;
    if (await isFresh(src, out)) {
      console.log(`precompress: ${rel}${ext} up to date`);
      continue;
    }
    const t = Date.now();
    const buf = await run();
    await writeFile(out, buf);
    console.log(
      `precompress: ${rel}${ext}  ${raw.length} -> ${buf.length}  (-${pct(buf.length, raw.length)}, ${Date.now() - t} ms)`
    );
  }
}

// Only checked when both files were actually read — a clone without the binaries
// has nothing to compare and must still build.
if (hashes.length === TARGETS.length) {
  const rev = await readFile(path.join(ROOT, 'src/lib/modelRev.ts'), 'utf8');
  // Scoped to the MODEL_HASH declaration rather than scanning the whole file for
  // hex-looking strings, so an unrelated constant cannot quietly join the list.
  const decl = rev.match(/MODEL_HASH[^=]*=\s*\[([^\]]*)\]/);
  const want = decl ? [...decl[1].matchAll(/'([0-9a-f]{12})'/g)].map((m) => m[1]) : [];
  if (want.length !== hashes.length || want.some((h, i) => h !== hashes[i])) {
    console.error(
      [
        '',
        'precompress: THE MODEL BINARIES CHANGED AND MODEL_REV DID NOT.',
        '',
        `  on disk:        [${hashes.map((h) => `'${h}'`).join(', ')}]`,
        `  in modelRev.ts: [${want.map((h) => `'${h}'`).join(', ')}]`,
        '',
        '  The model URLs are served immutable for a year and are busted only by',
        '  MODEL_REV, so shipping this as it stands would leave every returning',
        '  visitor on the old geometry until their cache expires.',
        '',
        '  In src/lib/modelRev.ts: bump MODEL_REV, and paste the on-disk hashes',
        '  above into MODEL_HASH.',
        '',
      ].join('\n')
    );
    process.exit(1);
  }
  console.log('precompress: model hashes match MODEL_HASH');
}
